version: '2'

services:

  traefik:
    image: traefik:latest
    command: --docker --docker.domain=TUDOMINIO.duckdns.org
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - "traefik.frontend.rule=Host:traefik.TUDOMINIO.duckdns.org"
      - "traefik.port=8080"
    container_name: traefik
    restart: always
    
      
    
networks:
  traefik:
    external: true
